### ISSUE TITLE
syling

### ISSUE THREAD

**Issue by Bibilidibipi** [Nexproc/Capstone-Proposal#3]
"Properly aligning subviews" shouldn't come last; this is much easier to do as you implement each part of a project. Please save yourself a lot of trouble and write css (use bootstrap) as you go!

**Comment by Nexproc** [comment]
I've moved the phases around so that I am now building the project outward form the NavBar instead of starting from somewhere in the center and filling in the sides. I might still need to go back and tweak the workload for the adjusted phases - but this will allow me to have an app that works and looks clean\* at each phase.

*Hopefully.
